module Constants
	BROADCAST_USER = 0

	SESSION_STATUS_OPEN = 0
	SESSION_STATUS_CLOSED = 1

	MESSAGE_STATUS_NORMAL = 0
	MESSAGE_STATUS_EDITED = 1
	MESSAGE_STATUS_DELETED = 2

	USER_TYPE_ADMIN = 0
	USER_TYPE_TRAINER = 1
	USER_TYPE_MEMBER = 2
end
